-- GameRadar community: run in Supabase SQL editor before enabling live writes.
create table if not exists community_profiles (id uuid primary key references auth.users on delete cascade, handle text unique not null check (char_length(handle) between 3 and 24), role text not null default 'member' check (role in ('member','moderator','admin')), created_at timestamptz not null default now());
create table if not exists community_posts (id uuid primary key default gen_random_uuid(), game_slug text, author_id uuid references community_profiles(id) on delete set null, title text not null check (char_length(title) between 12 and 180), body text not null check (char_length(body) between 20 and 10000), flair text not null default 'discussion', status text not null default 'pending' check (status in ('pending','published','removed')), score integer not null default 0, created_at timestamptz not null default now());
create table if not exists community_comments (id uuid primary key default gen_random_uuid(), post_id uuid not null references community_posts(id) on delete cascade, author_id uuid references community_profiles(id) on delete set null, parent_id uuid references community_comments(id) on delete cascade, body text not null check (char_length(body) between 2 and 5000), status text not null default 'pending' check (status in ('pending','published','removed')), score integer not null default 0, created_at timestamptz not null default now());
create table if not exists community_votes (user_id uuid references community_profiles(id) on delete cascade, post_id uuid references community_posts(id) on delete cascade, comment_id uuid references community_comments(id) on delete cascade, value smallint not null check (value in (-1,1)), primary key(user_id,post_id,comment_id), check ((post_id is null) <> (comment_id is null)));
alter table community_profiles enable row level security; alter table community_posts enable row level security; alter table community_comments enable row level security; alter table community_votes enable row level security;
create policy "public published posts" on community_posts for select using (status='published');
create policy "members submit posts" on community_posts for insert to authenticated with check (author_id=auth.uid() and status='pending');
create policy "public published comments" on community_comments for select using (status='published');
create policy "members submit comments" on community_comments for insert to authenticated with check (author_id=auth.uid() and status='pending');
