// 全站 UI 文案字典。三种语言的 key 必须完全对齐——写完记得对一下三份有没有漏 key，
// 漏了的话 t() 会在缺失语言里回退到中文（宁可显示中文也不要显示 undefined）。

export const UI = {
  zh: {
    tagline: "游戏攻略雷达",
    searchPlaceholder: "搜索游戏、开发商、类型…",
    searchAria: "搜索游戏",
    navUpcoming: "即将发行",
    navTrending: "本周热门",
    navRules: "收录规则",

    footerDesc: "每天自动收录待发行与热门游戏，套用固定模版。有深度 Wiki 的直达站点，其余生成结构化资料页 + 精选真实外链。发现优先，不做规模化薄内容。",
    footerBrowse: "浏览",
    footerAllGames: "全部游戏",
    footerGenres: "按类型浏览",
    footerPlatforms: "按平台浏览",
    footerRules: "收录规则",
    footerDataSource: "数据源 · IGDB",
    footerDraftRadar: "草稿雷达（内部）",
    footerMyWikis: "我的 Wiki",
    footerLegal: "独立域名，与深度 Wiki 风险隔离",

    heroEyebrow: "最近发行 · 头号追踪",
    heroCtaWiki: "进入深度 Wiki",
    heroCtaInfo: "查看资料",
    countdownLabel: "距离发行",
    unitDays: "天",
    unitHours: "时",
    unitMinutes: "分",
    unitSeconds: "秒",

    tabAll: "全部",
    tabUpcoming: "即将发行",
    tabTrending: "本周热门",
    tabOwned: "我的 Wiki",
    railUpcoming: "即将发行",
    railTrending: "本周热门",
    railAll: "全部游戏",
    countSuffix: "款",
    emptyTitle: "没有匹配的游戏",
    emptyBody: "换个关键词，或看看即将发行的作品。",
    searchResultsFor: (q) => `“${q}” 的结果`,

    pillOwned: "我的 Wiki",
    pillNav: "资料页",
    pillLive: "已上线",
    ctaOwned: "进入 Wiki",
    ctaNav: "查看资料",

    relLive: "已上线",
    relTBA: "待定 TBA",
    relReleased: "已发行",
    relToday: "今日发行",
    relDaysUntil: (d) => `距发行 ${d} 天`,

    breadcrumbBack: "← 返回 GameRadar",
    draftBanner: "⚠ 这是草稿页：资料完整度还不够公开推荐的门槛，仅供内部预览，不会被搜索引擎收录，也不会出现在首页。",
    factReleaseDate: "发行日期",
    factDeveloper: "开发商",
    factPublisher: "发行商",
    factPlatforms: "平台",
    factGenres: "类型",
    factHype: "热度",
    relatedLinks: "相关链接",
    noLinks: "暂无外链",
    detailNote: "这是聚合导航页：结构化事实 + 人工精选的真实外链。当这款游戏热度足够、值得投入原创内容时，会为它建立独立深度 Wiki，届时这里会替换成直链。",

    linkOfficial: "官方网站", linkOfficialSub: "最权威的一手信息",
    linkSteam: "Steam 商店页", linkSteamSub: "配置 · 价格 · 评测",
    linkReddit: "Reddit 社区", linkRedditSub: "玩家讨论与情报",
    linkDiscord: "官方 Discord", linkDiscordSub: "实时社群",
    linkFanwiki: "粉丝 Wiki", linkFanwikiSub: "社区维护的资料库",
    linkEpicgames: "Epic 商店页", linkEpicgamesSub: "配置 · 价格",
    linkGog: "GOG 商店页", linkGogSub: "无 DRM 版本",

    genresPageTitle: "按类型浏览",
    platformsPageTitle: "按平台浏览",
    draftRadarTitle: "草稿雷达",
    draftRadarDesc: (n) => `资料完整度不够公开门槛的候选游戏，共 ${n} 款。这里只有你能看到，抓取脚本每天更新。`,
    draftRadarEmptyTitle: "暂时没有草稿",
    draftRadarEmptyBody: "抓取脚本跑过之后，资料不够完整的候选游戏会出现在这里。",

    metaDescHome: "待发行与热门游戏的攻略索引，每天自动收录，直达深度 Wiki 与精选资料。",
    gameMetaTitle: (t) => `${t} 攻略资料 | GameRadar`,
    gameMetaDesc: (t, dev, pub) => `${t}发行日期、平台、类型与官方链接汇总——${dev} 开发${pub ? `，${pub} 发行` : ""}。`,
    genreMetaDesc: (label, n) => `收录 ${n} 款${label}类型游戏，涵盖即将发行与近期热门作品，附平台、开发商与官方链接。`,
    platformMetaDesc: (label, n) => `收录 ${n} 款 ${label} 平台游戏，涵盖即将发行与近期热门作品，附类型、开发商与官方链接。`,
  },

  en: {
    tagline: "Game Guide Radar",
    searchPlaceholder: "Search games, developers, genres…",
    searchAria: "Search games",
    navUpcoming: "Upcoming",
    navTrending: "Trending",
    navRules: "How we index",

    footerDesc: "Automatically tracks upcoming and trending games every day using a fixed template. Games with a deep wiki link straight there; everything else gets a structured reference page with hand-picked real links. Discovery first — no scaled thin content.",
    footerBrowse: "Browse",
    footerAllGames: "All games",
    footerGenres: "Browse by genre",
    footerPlatforms: "Browse by platform",
    footerRules: "How we index",
    footerDataSource: "Data source · IGDB",
    footerDraftRadar: "Draft radar (internal)",
    footerMyWikis: "My wikis",
    footerLegal: "Separate domain, isolated from the deep wikis' SEO risk",

    heroEyebrow: "Next release · Top pick",
    heroCtaWiki: "Go to the deep wiki",
    heroCtaInfo: "View details",
    countdownLabel: "Time to release",
    unitDays: "Days",
    unitHours: "Hrs",
    unitMinutes: "Min",
    unitSeconds: "Sec",

    tabAll: "All",
    tabUpcoming: "Upcoming",
    tabTrending: "Trending",
    tabOwned: "My wikis",
    railUpcoming: "Upcoming",
    railTrending: "Trending this week",
    railAll: "All games",
    countSuffix: "games",
    emptyTitle: "No matching games",
    emptyBody: "Try a different keyword, or check out what's coming up.",
    searchResultsFor: (q) => `Results for "${q}"`,

    pillOwned: "My wiki",
    pillNav: "Reference",
    pillLive: "Live",
    ctaOwned: "Go to wiki",
    ctaNav: "View details",

    relLive: "Out now",
    relTBA: "TBA",
    relReleased: "Released",
    relToday: "Out today",
    relDaysUntil: (d) => `${d} days to go`,

    breadcrumbBack: "← Back to GameRadar",
    draftBanner: "⚠ This is a draft page: it hasn't cleared our completeness bar yet, so it's for internal preview only — not indexed by search engines, and not shown on the homepage.",
    factReleaseDate: "Release date",
    factDeveloper: "Developer",
    factPublisher: "Publisher",
    factPlatforms: "Platforms",
    factGenres: "Genres",
    factHype: "Hype",
    relatedLinks: "Related links",
    noLinks: "No links available yet",
    detailNote: "This is an aggregated reference page: structured facts plus hand-picked real links. Once this game is popular enough to justify original coverage, it'll get its own deep wiki and this link will point straight there.",

    linkOfficial: "Official site", linkOfficialSub: "The most authoritative source",
    linkSteam: "Steam page", linkSteamSub: "Specs · price · reviews",
    linkReddit: "Reddit community", linkRedditSub: "Player discussion & intel",
    linkDiscord: "Official Discord", linkDiscordSub: "Live community",
    linkFanwiki: "Fan wiki", linkFanwikiSub: "Community-maintained reference",
    linkEpicgames: "Epic Games page", linkEpicgamesSub: "Specs · price",
    linkGog: "GOG page", linkGogSub: "DRM-free version",

    genresPageTitle: "Browse by genre",
    platformsPageTitle: "Browse by platform",
    draftRadarTitle: "Draft radar",
    draftRadarDesc: (n) => `${n} candidate game(s) that haven't cleared the public completeness bar yet. Only you can see this — updated daily by the fetch script.`,
    draftRadarEmptyTitle: "No drafts right now",
    draftRadarEmptyBody: "Once the fetch script runs, thin-data candidate games will show up here.",

    metaDescHome: "A discovery index for upcoming and trending games — refreshed daily, linking straight to deep wikis and hand-picked references.",
    gameMetaTitle: (t) => `${t} — release date, platforms & links | GameRadar`,
    gameMetaDesc: (t, dev, pub) => `${t} release date, platforms, genres and official links — developed by ${dev}${pub ? `, published by ${pub}` : ""}.`,
    genreMetaDesc: (label, n) => `${n} ${label} games, covering upcoming releases and current trending titles, with platforms, developers and official links.`,
    platformMetaDesc: (label, n) => `${n} games on ${label}, covering upcoming releases and current trending titles, with genres, developers and official links.`,
  },

  es: {
    tagline: "Radar de Guías de Videojuegos",
    searchPlaceholder: "Buscar juegos, desarrolladores, géneros…",
    searchAria: "Buscar juegos",
    navUpcoming: "Próximamente",
    navTrending: "Tendencias",
    navRules: "Cómo indexamos",

    footerDesc: "Rastrea automáticamente cada día los juegos próximos y en tendencia con una plantilla fija. Los juegos con wiki propia enlazan directo allí; el resto recibe una ficha estructurada con enlaces reales seleccionados a mano. Prioridad al descubrimiento, sin contenido superficial a escala.",
    footerBrowse: "Explorar",
    footerAllGames: "Todos los juegos",
    footerGenres: "Explorar por género",
    footerPlatforms: "Explorar por plataforma",
    footerRules: "Cómo indexamos",
    footerDataSource: "Fuente de datos · IGDB",
    footerDraftRadar: "Radar de borradores (interno)",
    footerMyWikis: "Mis wikis",
    footerLegal: "Dominio independiente, aislado del riesgo SEO de las wikis propias",

    heroEyebrow: "Próximo lanzamiento · Destacado",
    heroCtaWiki: "Ir a la wiki completa",
    heroCtaInfo: "Ver ficha",
    countdownLabel: "Tiempo para el lanzamiento",
    unitDays: "Días",
    unitHours: "Hs",
    unitMinutes: "Min",
    unitSeconds: "Seg",

    tabAll: "Todos",
    tabUpcoming: "Próximamente",
    tabTrending: "Tendencias",
    tabOwned: "Mis wikis",
    railUpcoming: "Próximamente",
    railTrending: "Tendencias de la semana",
    railAll: "Todos los juegos",
    countSuffix: "juegos",
    emptyTitle: "No hay juegos que coincidan",
    emptyBody: "Prueba con otra palabra clave o mira lo que viene próximamente.",
    searchResultsFor: (q) => `Resultados para "${q}"`,

    pillOwned: "Mi wiki",
    pillNav: "Ficha",
    pillLive: "Disponible",
    ctaOwned: "Ir a la wiki",
    ctaNav: "Ver ficha",

    relLive: "Ya disponible",
    relTBA: "Por confirmar",
    relReleased: "Lanzado",
    relToday: "Se lanza hoy",
    relDaysUntil: (d) => `Faltan ${d} días`,

    breadcrumbBack: "← Volver a GameRadar",
    draftBanner: "⚠ Esta es una página en borrador: aún no alcanza el umbral de calidad para publicarse. Es solo una vista previa interna — no aparece en buscadores ni en la portada.",
    factReleaseDate: "Fecha de lanzamiento",
    factDeveloper: "Desarrollador",
    factPublisher: "Distribuidor",
    factPlatforms: "Plataformas",
    factGenres: "Géneros",
    factHype: "Expectativa",
    relatedLinks: "Enlaces relacionados",
    noLinks: "Todavía no hay enlaces disponibles",
    detailNote: "Esta es una ficha de referencia agregada: datos estructurados más enlaces reales seleccionados a mano. Cuando este juego tenga suficiente relevancia para justificar contenido original, tendrá su propia wiki y este enlace apuntará directamente allí.",

    linkOfficial: "Sitio oficial", linkOfficialSub: "La fuente más autorizada",
    linkSteam: "Página de Steam", linkSteamSub: "Requisitos · precio · reseñas",
    linkReddit: "Comunidad en Reddit", linkRedditSub: "Debate e información de jugadores",
    linkDiscord: "Discord oficial", linkDiscordSub: "Comunidad en vivo",
    linkFanwiki: "Wiki de fans", linkFanwikiSub: "Referencia mantenida por la comunidad",
    linkEpicgames: "Página en Epic Games", linkEpicgamesSub: "Requisitos · precio",
    linkGog: "Página en GOG", linkGogSub: "Versión sin DRM",

    genresPageTitle: "Explorar por género",
    platformsPageTitle: "Explorar por plataforma",
    draftRadarTitle: "Radar de borradores",
    draftRadarDesc: (n) => `${n} juego(s) candidato(s) que aún no superan el umbral público de calidad. Solo tú puedes ver esto — se actualiza a diario.`,
    draftRadarEmptyTitle: "No hay borradores por ahora",
    draftRadarEmptyBody: "Cuando el script se ejecute, aquí aparecerán los juegos candidatos con datos incompletos.",

    metaDescHome: "Un índice de descubrimiento de juegos próximos y en tendencia, actualizado a diario, con enlaces directos a wikis completas y fichas seleccionadas.",
    gameMetaTitle: (t) => `${t} — fecha de lanzamiento, plataformas y enlaces | GameRadar`,
    gameMetaDesc: (t, dev, pub) => `${t}: fecha de lanzamiento, plataformas, géneros y enlaces oficiales — desarrollado por ${dev}${pub ? `, distribuido por ${pub}` : ""}.`,
    genreMetaDesc: (label, n) => `${n} juegos de ${label}, entre próximos lanzamientos y títulos en tendencia, con plataformas, desarrolladores y enlaces oficiales.`,
    platformMetaDesc: (label, n) => `${n} juegos en ${label}, entre próximos lanzamientos y títulos en tendencia, con géneros, desarrolladores y enlaces oficiales.`,
  },
};

/**
 * t(locale, key, ...args) —— 取文案，缺了就退回中文而不是显示 undefined。
 * 如果 args 有值且对应的文案是函数（比如 relDaysUntil），就调用它拿最终字符串。
 */
export function t(locale, key, ...args) {
  const dict = UI[locale] || UI.zh;
  const value = key in dict ? dict[key] : UI.zh[key];
  return typeof value === "function" ? value(...args) : value;
}
