export const P2 = {
  en: {
    tools: "Tools", myRadar: "My Radar", compareGames: "Compare games",
    radarTitle: "My release radar", radarIntro: "Review the games saved in this browser, see the next confirmed release, remove old picks, or export dated games to your calendar.",
    savedGames: "Saved games", nextRelease: "Next confirmed release", datedGames: "With confirmed dates", noSaved: "Your radar is empty", noSavedIntro: "Add games from a game page or the release planner. Your list stays in this browser and is never uploaded.", browseGames: "Browse games", releasePlanner: "Open release planner", clearAll: "Clear radar", remove: "Remove", confirmClear: "Remove every game from this browser's radar?", localOnly: "Saved locally in this browser", exportCalendar: "Export dated games (.ics)",
    compareTitle: "Game comparison tool", compareIntro: "Compare up to three tracked games using confirmed release dates, platforms, genres, studios, and guide coverage. No ratings or unconfirmed claims are added.", selectGame: "Select a game", gameSlot: "Game", shareComparison: "Copy comparison link", linkCopied: "Comparison link copied", addToCompare: "Compare this game", comparisonTable: "Comparison", field: "Field", releaseDate: "Release date", status: "Status", developer: "Developer", publisher: "Publisher", platforms: "Platforms", genres: "Genres", coverage: "Guide coverage", deepGuide: "In-depth wiki", reference: "Reference hub", upcoming: "Upcoming", released: "Released", tba: "TBA", sharedPlatforms: "Shared platforms", noSharedPlatforms: "No confirmed platform overlap", comparisonSummary: "Quick comparison", chooseTwo: "Choose at least two different games to compare.",
    howTitle: "What this comparison checks", howRelease: "Release timing", howReleaseText: "Confirmed dates are shown side by side, with TBA kept separate from dated releases.", howPlatform: "Platform overlap", howPlatformText: "See where every selected game is confirmed and which platforms they share.", howCoverage: "Guide depth", howCoverageText: "Distinguish a deep independent wiki from a structured reference hub before opening a game.",
    genresIntro: "Explore the game catalog by genre. Counts reflect the current structured dataset and only useful, sufficiently populated English genre pages enter search.", platformsIntro: "Explore confirmed platform availability across the catalog. Platform pages are generated from structured game records and use a minimum-content threshold.", genreCollectionIntro: "Browse tracked games currently classified under {label}.", platformCollectionIntro: "Browse tracked games with confirmed availability on {label}.",
  },
  zh: {
    tools: "工具", myRadar: "我的雷达", compareGames: "游戏对比",
    radarTitle: "我的发行雷达", radarIntro: "查看保存在当前浏览器中的游戏、下一款已确认发行的作品，清理关注项或导出日历。",
    savedGames: "已关注游戏", nextRelease: "下一款已定档游戏", datedGames: "已确认日期", noSaved: "关注雷达还是空的", noSavedIntro: "可以从游戏详情页或发行计划器添加。关注数据只保存在当前浏览器，不会上传。", browseGames: "浏览游戏", releasePlanner: "打开发行计划器", clearAll: "清空雷达", remove: "移除", confirmClear: "从当前浏览器清空全部关注游戏？", localOnly: "仅保存在当前浏览器", exportCalendar: "导出已定档游戏（.ics）",
    compareTitle: "游戏对比工具", compareIntro: "使用已确认的发行日期、平台、类型、开发商和攻略覆盖，对比最多三款游戏；不加入评分或未确认说法。", selectGame: "选择游戏", gameSlot: "游戏", shareComparison: "复制对比链接", linkCopied: "对比链接已复制", addToCompare: "对比这款游戏", comparisonTable: "对比结果", field: "项目", releaseDate: "发行日期", status: "状态", developer: "开发商", publisher: "发行商", platforms: "平台", genres: "类型", coverage: "攻略覆盖", deepGuide: "深度独立 Wiki", reference: "资料中心", upcoming: "即将发行", released: "已经发行", tba: "待定", sharedPlatforms: "共同平台", noSharedPlatforms: "没有已确认的共同平台", comparisonSummary: "快速结论", chooseTwo: "请至少选择两款不同的游戏。",
    howTitle: "对比包含什么", howRelease: "发行时间", howReleaseText: "并列展示已确认日期，尚未定档的游戏会与确定日期明确区分。", howPlatform: "平台重合", howPlatformText: "查看每款游戏确认登陆的平台，以及它们共同覆盖的平台。", howCoverage: "攻略深度", howCoverageText: "打开游戏前即可区分深度独立 Wiki 与结构化资料中心。",
    genresIntro: "按类型浏览当前游戏库。数量来自结构化数据，只有内容充足且有实际浏览价值的英文类型页才进入搜索索引。", platformsIntro: "按已确认平台浏览游戏库。平台页由结构化游戏资料生成，并设置最低内容数量门槛。", genreCollectionIntro: "浏览当前归类为 {label} 的游戏。", platformCollectionIntro: "浏览已确认登陆 {label} 的游戏。",
  },
  de: {
    tools: "Tools", myRadar: "Mein Radar", compareGames: "Spiele vergleichen",
    radarTitle: "Mein Release-Radar", radarIntro: "Gespeicherte Spiele, den nächsten bestätigten Release und datierte Kalendereinträge in diesem Browser verwalten.",
    savedGames: "Gespeicherte Spiele", nextRelease: "Nächster bestätigter Release", datedGames: "Mit bestätigtem Termin", noSaved: "Dein Radar ist leer", noSavedIntro: "Füge Spiele auf einer Spielseite oder im Release-Planer hinzu. Die Liste bleibt ausschließlich in diesem Browser.", browseGames: "Spiele durchsuchen", releasePlanner: "Release-Planer öffnen", clearAll: "Radar leeren", remove: "Entfernen", confirmClear: "Alle Spiele aus dem Radar dieses Browsers entfernen?", localOnly: "Lokal in diesem Browser gespeichert", exportCalendar: "Datierte Spiele exportieren (.ics)",
    compareTitle: "Spielevergleich", compareIntro: "Vergleiche bis zu drei erfasste Spiele anhand bestätigter Termine, Plattformen, Genres, Studios und Guide-Abdeckung – ohne unbestätigte Wertungen.", selectGame: "Spiel auswählen", gameSlot: "Spiel", shareComparison: "Vergleichslink kopieren", linkCopied: "Vergleichslink kopiert", addToCompare: "Dieses Spiel vergleichen", comparisonTable: "Vergleich", field: "Merkmal", releaseDate: "Veröffentlichung", status: "Status", developer: "Entwickler", publisher: "Publisher", platforms: "Plattformen", genres: "Genres", coverage: "Guide-Abdeckung", deepGuide: "Ausführliches Wiki", reference: "Referenz-Hub", upcoming: "Demnächst", released: "Veröffentlicht", tba: "Offen", sharedPlatforms: "Gemeinsame Plattformen", noSharedPlatforms: "Keine bestätigte Plattformüberschneidung", comparisonSummary: "Kurzvergleich", chooseTwo: "Wähle mindestens zwei verschiedene Spiele.",
    howTitle: "Was der Vergleich prüft", howRelease: "Release-Zeitpunkt", howReleaseText: "Bestätigte Termine stehen nebeneinander; undatierte Releases bleiben klar getrennt.", howPlatform: "Plattformüberschneidung", howPlatformText: "Zeigt bestätigte Plattformen und die Schnittmenge der ausgewählten Spiele.", howCoverage: "Guide-Tiefe", howCoverageText: "Erkenne vor dem Öffnen, ob ein tiefes unabhängiges Wiki oder ein strukturierter Referenz-Hub vorliegt.",
    genresIntro: "Durchsuche den Katalog nach Genre. Nur ausreichend gefüllte und nützliche englische Genreseiten werden indexiert.", platformsIntro: "Durchsuche bestätigte Plattformverfügbarkeit. Plattformseiten entstehen aus strukturierten Datensätzen und haben eine Mindestmenge.", genreCollectionIntro: "Erfasste Spiele in der Kategorie {label}.", platformCollectionIntro: "Erfasste Spiele mit bestätigter Verfügbarkeit auf {label}.",
  },
  es: {
    tools: "Herramientas", myRadar: "Mi radar", compareGames: "Comparar juegos",
    radarTitle: "Mi radar de lanzamientos", radarIntro: "Gestiona los juegos guardados en este navegador, el próximo lanzamiento confirmado y la exportación al calendario.",
    savedGames: "Juegos guardados", nextRelease: "Próximo lanzamiento confirmado", datedGames: "Con fecha confirmada", noSaved: "Tu radar está vacío", noSavedIntro: "Añade juegos desde su ficha o el planificador. La lista permanece únicamente en este navegador.", browseGames: "Explorar juegos", releasePlanner: "Abrir planificador", clearAll: "Vaciar radar", remove: "Eliminar", confirmClear: "¿Eliminar todos los juegos del radar de este navegador?", localOnly: "Guardado localmente en este navegador", exportCalendar: "Exportar juegos con fecha (.ics)",
    compareTitle: "Comparador de juegos", compareIntro: "Compara hasta tres juegos mediante fechas, plataformas, géneros, estudios y cobertura confirmados, sin valoraciones ni afirmaciones no verificadas.", selectGame: "Seleccionar juego", gameSlot: "Juego", shareComparison: "Copiar enlace", linkCopied: "Enlace copiado", addToCompare: "Comparar este juego", comparisonTable: "Comparación", field: "Campo", releaseDate: "Lanzamiento", status: "Estado", developer: "Desarrollador", publisher: "Editor", platforms: "Plataformas", genres: "Géneros", coverage: "Cobertura", deepGuide: "Wiki detallada", reference: "Centro de referencia", upcoming: "Próximamente", released: "Publicado", tba: "Sin fecha", sharedPlatforms: "Plataformas compartidas", noSharedPlatforms: "Sin plataformas confirmadas en común", comparisonSummary: "Comparación rápida", chooseTwo: "Selecciona al menos dos juegos diferentes.",
    howTitle: "Qué comprueba", howRelease: "Calendario", howReleaseText: "Muestra fechas confirmadas en paralelo y separa claramente los juegos sin fecha.", howPlatform: "Coincidencia de plataformas", howPlatformText: "Muestra dónde está confirmado cada juego y qué plataformas comparten.", howCoverage: "Profundidad de guía", howCoverageText: "Distingue una wiki independiente detallada de una ficha estructurada antes de abrir el juego.",
    genresIntro: "Explora el catálogo por género. Solo las páginas inglesas útiles y con suficientes juegos se indexan.", platformsIntro: "Explora la disponibilidad confirmada por plataforma. Las páginas se generan con datos estructurados y un umbral mínimo.", genreCollectionIntro: "Juegos registrados dentro de {label}.", platformCollectionIntro: "Juegos registrados con disponibilidad confirmada en {label}.",
  },
  ja: {
    tools: "ツール", myRadar: "マイレーダー", compareGames: "ゲーム比較",
    radarTitle: "発売マイレーダー", radarIntro: "このブラウザに保存したゲーム、次の確定発売日、カレンダー書き出しをまとめて管理します。",
    savedGames: "保存したゲーム", nextRelease: "次の発売予定", datedGames: "発売日確定済み", noSaved: "レーダーは空です", noSavedIntro: "ゲームページまたは発売プランナーから追加できます。リストはこのブラウザだけに保存され、送信されません。", browseGames: "ゲームを探す", releasePlanner: "発売プランナーを開く", clearAll: "レーダーを消去", remove: "削除", confirmClear: "このブラウザのレーダーをすべて消去しますか？", localOnly: "このブラウザ内だけに保存", exportCalendar: "確定済みをカレンダーへ（.ics）",
    compareTitle: "ゲーム比較ツール", compareIntro: "確認済みの発売日、対応機種、ジャンル、開発会社、攻略範囲で最大3作品を比較します。未確認の評価は追加しません。", selectGame: "ゲームを選択", gameSlot: "ゲーム", shareComparison: "比較リンクをコピー", linkCopied: "比較リンクをコピーしました", addToCompare: "このゲームを比較", comparisonTable: "比較結果", field: "項目", releaseDate: "発売日", status: "状況", developer: "開発会社", publisher: "販売会社", platforms: "対応機種", genres: "ジャンル", coverage: "攻略範囲", deepGuide: "詳細Wiki", reference: "情報ハブ", upcoming: "発売予定", released: "発売済み", tba: "未定", sharedPlatforms: "共通プラットフォーム", noSharedPlatforms: "確認済みの共通機種はありません", comparisonSummary: "クイック比較", chooseTwo: "異なるゲームを2本以上選んでください。",
    howTitle: "比較する内容", howRelease: "発売時期", howReleaseText: "確定日を横並びで表示し、発売日未定の作品を明確に分けます。", howPlatform: "対応機種の重なり", howPlatformText: "各作品の確認済み機種と、共通して遊べる機種を確認できます。", howCoverage: "攻略の深さ", howCoverageText: "詳細な独立Wikiと構造化された情報ハブを開く前に見分けられます。",
    genresIntro: "ジャンル別にゲームを探せます。十分な掲載数と実用性がある英語ページのみ検索対象にします。", platformsIntro: "確認済み対応機種別にゲームを探せます。構造化データと最低掲載数に基づき生成します。", genreCollectionIntro: "{label}に分類される追跡中のゲームです。", platformCollectionIntro: "{label}での発売が確認されているゲームです。",
  },
};

export function p2Text(locale, key, vars = {}) {
  let value = (P2[locale] || P2.en)[key] ?? P2.en[key] ?? key;
  for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
}
